[buildPlans.iosevka-sans]
family = "Iosevka Sans"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false
no-ligation = false

[buildPlans.iosevka-sans.variants.design]
zero = "dotted"
asterisk = "penta-low"
number-sign = "slanted-open"
ampersand = "upper-open"
dollar = "open"

[buildPlans.iosevka-sans.variants.italic]
