[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false
no-ligation = true

[buildPlans.iosevka-custom.variants.design]
zero = "dotted"
asterisk = "penta-low"
number-sign = "slanted-open"
ampersand = "upper-open"
dollar = "open"

[buildPlans.iosevka-custom.variants.italic]
