[buildPlans.iosevka-sans]
family = "Iosevka Sans"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false
no-ligation = false

[buildPlans.iosevka-sans.variants.design]
zero = "dotted"
asterisk = "penta-low"
number-sign = "slanted-open"
ampersand = "upper-open"
percent = "dots"
dollar = "open"
bar = "natural-slope"
f = "flat-hook-serifless"
l = "tailed-serifed"
t = "flat-hook"
j = "flat-hook-serifed"
g = "double-storey"

[buildPlans.iosevka-sans.variants.italic]
f = "flat-hook-tailed"
j = "serifed"
g = "single-storey-serifless"
