[buildPlans.iosevka-sans]
family = "Iosevka Sans"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false
no-ligation = false

[buildPlans.iosevka-sans.variants.design]
zero = "slashed-split"
g = "double-storey"
asterisk = "penta-low"
number-sign = "slanted-open"
ampersand = "upper-open"
dollar = "open"
bar = "natural-slope"
l = "zshaped"
paren = "large-contour"

[buildPlans.iosevka-sans.variants.italic]
l = "tailed-serifed"
