set nocompatible
filetype off

filetype plugin indent on
set encoding=utf-8

" Tab stuff
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab
set autoindent

" Show whitespace
set list
set listchars=tab:>\ ,trail:·,nbsp:·,space:·
autocmd FileType nerdtree setlocal nolist

"Things
set number
set hlsearch
set incsearch
set noerrorbells
set showmatch
set cursorline
set showcmd
set lazyredraw

" Wild menu/ completion
set wildmenu
set wildmode=longest:full,full
set omnifunc=syntaxcomplete#Complete

" Mouse
set mouse=a
set ttymouse=xterm2 " allows window resizing in tmux

" Backspace
set backspace=indent,eol,start

" Location for swap files
set directory^=$HOME/.vim/tmp//

" Switch buffers without having to save
set hidden

syntax on
colorscheme base16-two

" Always show statusline
set laststatus=2

" Full height vertical separator
set fillchars+=vert:│


set statusline=
set statusline +=%f\ %m\ %r\ %*     " file name, modified, readonly
set statusline +=%=                 " left/ right separator
set statusline +=%c\ :\ %l/%L%*     " cursor column, current line, total

" vim-go settings
let g:go_fmt_command = "goimports"
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1

" Rust settings
let g:rustfmt_autosave = 1

" NERDTree settings
" Expand dir, open files with single click
let NERDTreeMouseMode = 3
let NERDTreeShowHidden = 1
let NERDTreeMinimalUI = 1
highlight NERDTreeCWD ctermfg=green

" Shortcuts

" Remap leader to ,
let mapleader = ","

" Move to windows with Ctrl-key
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Ctrl-space to autocomplete
inoremap <C-@> <C-x><C-o>

" Toggle nerdtree with leader-n
map <leader>n :NERDTreeToggle<CR>

" Cycle betwen buffers using leader-a and leader-s
map <leader>a :bp<CR>
map <leader>s :bn<CR>

" Delete current buffer with leader-bd
map <leader>bd :bd<CR>

" Clear search hl with leader-c
map <leader>c :nohlsearch<CR>
