#!/usr/bin/env bash

mon_current() {
    local outstr
    outstr=$(ddcutil getvcp 10)
    local nums
    nums=$(echo -e "$outstr" | sed -e 's/[^0-9]/ /g' -e 's/^ *//g' -e 's/ *$//g' | tr -s ' ')
    echo "$nums" | cut -d " " -f 3
}

num_displays() {
    ddcutil detect | grep "Display" -c
}

case $1 in
    "monitor")
    case $2 in
        "up")
        amount="${3:-2}"
        curr=$(mon_current)
        for i in $(num_displays); do
            ddcutil setvcp 10 $(( curr + amount )) --display "$i"
        done
        ;;
        "down")
        amount="${3:-2}"
        curr=$(mon_current)
        for i in $(num_displays); do
            ddcutil setvcp 10 $(( curr - amount )) --display "$i"
        done
        ;;
        "set")
        : "${3?"Usage: $0 monitor set PERCENT"}"
        if [ -n "$4" ]; then
            ddcutil setvcp 10 "$3" --display "$4"
        else
            for i in $(num_displays); do
                ddcutil setvcp 10 "$3" --display "$i"
            done
        fi
        ;;
    esac
    ;;
    "laptop")
    case $2 in
        "up")
        amount="${3:-2}"
        xbacklight -inc "$amount" -fps 60
        ;;
        "down")
        amount="${3:-2}"
        xbacklight -dec "$amount" -fps 60
        ;;
        "set")
        : "${3?"Usage: $0 laptop set PERCENT"}"
        xbacklight -set "$3" -fps 60
        ;;
    esac
    ;;
esac
