#!/usr/bin/env bash

laptop_dpi=222
monitor_dpi=148

function set_dpi() {
   echo "Xft.dpi: $1" | xrdb -merge
   echo "*dpi: $1" | xrdb -merge
}

if [ "$#" -eq 1 ]; then
   case $1 in
       "laptop")
           set_dpi $laptop_dpi
           ;;
       "monitor")
           set_dpi $monitor_dpi
           ;;
       *)
           set_dpi "$1"
           ;;
   esac
else
    print "Invalid number of arguments"
fi
