#!/usr/bin/env bash

set -e

file=screenshot_$(date -Iseconds).png

maim --select --hidecursor | tee ~/Pictures/screenshots/$file | xclip -selection clipboard -t image/png
notify-send "Screenshot taken" "$file"
