#!/usr/bin/env bash

trap '' HUP

if pgrep -x redshift > /dev/null; then
    pkill redshift
    echo "redshift killed"
else
    nohup redshift &> /tmp/redshift.nohup.out &
    echo "redshift started"
fi
