xsetroot -cursor_name left_ptr
hsetroot -solid "#282c34"
compton -CGb -o 0 --no-fading-openclose -d :0

if [ "$HOSTNAME" = "system12" ]; then
    xrandr --dpi 120
fi;

xrdb ~/.Xresources
xmodmap ~/.xmodmap

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

dunst&

exec xmonad
