xsetroot -cursor_name left_ptr
hsetroot -solid "#282c34"

xrdb ~/.Xresources

case $HOSTNAME in
    "system22")
        echo "Xft.dpi: 144" | xrdb -merge
        echo "*dpi: 144" | xrdb -merge
        if [ -f ~/.icm/Y2XND_LQ156D1.icm ]; then
            xcalib ~/.icm/Y2XND_LQ156D1.icm
        fi
        ;;
esac

xmodmap ~/.xmodmap

dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

dunst&

# Set up lockscreen
xset s 300 5 # Lock after 5 minutes
xss-lock -l -- i3lock -c 1b2229&

exec xmonad
