xsetroot -cursor_name left_ptr
hsetroot -solid "#CFCFCF"

xrdb ~/.Xresources

case $HOSTNAME in
    "system22")
        dpi laptop
        ;;
    "system7")
        dpi monitor
        ;;
esac

# Change caplock to left control
mm

dbus-update-activation-environment --systemd DISPLAY
eval $(ssh-agent -s)
export SSH_AUTH_SOCK

redshift&
dunst&

# Set up lockscreen
xset s 300 5 # Lock after 5 minutes
export XSECURELOCK_PASSWORD_PROMPT=time
export XSECURELOCK_FONT="Source Sans Pro"
xss-lock -l -- xsecurelock&

exec xmonad
