#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export PATH=$PATH:$HOME/.bin/:$HOME/.local/bin/

export EDITOR=editor

export GOPATH=$HOME/.go
export GOPROXY=direct

export JULIA_NUM_THREADS=16

export PATH=$PATH:$HOME/.go/bin
export PATH=$PATH:/usr/local/go/bin

export PATH=$PATH:$HOME/.cargo/bin

export PATH=$PATH:$HOME/.elan/bin

# Prefer bins managed by ghcup over system bins. System bins still there for xmonad, I
# don't want to try to fix that right now.
export PATH=$HOME/.ghcup/bin:$PATH

alias mm='xmodmap ~/.xmodmap'

alias red="redshift -x && redshift -O"
alias redx="redshift -x"

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '
